/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 734e995a33d3b717da2e2cd309d31aee)
interface __BaseEnv_Env {
	EXCHANGE_RATES: KVNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
